- hiring-portal/src/Components/Navbar.jsx
#12 
redirect to home page issue fixed !
https://github.com/user-attachments/assets/03a4056f-f94d-4fb7-9256-6cb07993aa83
**Checklist:**
> redirect to home page functionality

- hiring-portal/src/CSS/signin.css
#14 
added Media queries to Signin page to make it responsive
> Login page made responsive

- hiring-portal/src/Components/Footer.jsx
solved issue #7 and #10
updated the links with the icons and an old Twitter logo change to x
> Update Footer links

- hiring-portal/src/CSS/footer.css
- hiring-portal/src/CSS/herosection.css
- hiring-portal/src/CSS/interview.css
- hiring-portal/src/CSS/middleview.css
- hiring-portal/src/CSS/navbar.css
- hiring-portal/src/CSS/postview.css
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/Homepage.jsx
- hiring-portal/src/Components/MiddleView.jsx
- hiring-portal/src/Components/Navbar.jsx
#38 
Make home page responsive to mobile device !
- [ ✔️] Enhancement
https://github.com/user-attachments/assets/c793a0d7-3eca-43ae-acce-9196f5681c75
> Make home page reponsive 

- hiring-portal/src/CSS/navbar.css
- hiring-portal/src/CSS/signup.css
- hiring-portal/src/Components/Signup.jsx
Reverts Yashgabani845/hiring-portal#37
> Revert "Responzive signUp Form and improvement of CSS"

- hiring-portal/src/CSS/footer.css
- hiring-portal/src/CSS/herosection.css
- hiring-portal/src/CSS/interview.css
- hiring-portal/src/CSS/middleview.css
- hiring-portal/src/CSS/navbar.css
- hiring-portal/src/CSS/postview.css
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/Homepage.jsx
- hiring-portal/src/Components/MiddleView.jsx
- hiring-portal/src/Components/Navbar.jsx
Reverts Yashgabani845/hiring-portal#42
> Revert "Make home page reponsive "

- hiring-portal/src/CSS/testimonial.css
- hiring-portal/src/Components/Homepage.jsx
- hiring-portal/src/Components/Testimonial.jsx
**Issue Reference:** Added Testimonial section to the website
This feature introduces a vibrant testimonial section to HireHub, aimed at enhancing user trust and engagement.
**Screenshots:** After
**Checklist:**
> Added dynamic and engaging testimonial section.

- et --hard abc123
- hiring-portal/src/CSS/profile.css
- hiring-portal/src/Components/Profile.jsx
#51 
Before 
After merging this pull request
- [✔️ ] Enhancement
**Checklist:**
- [✔️ ] I have tested my changes and verified that they work
- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have commented my code, particularly in hard-to-understand areas
- [ ✔️] I have made corresponding changes to the documentation
- [ ✔️] My changes generate no new warnings
- [ ✔️] I have added tests that prove my fix is effective or that my feature works
- [ ✔️] New and existing unit tests pass locally with my changes
> Enhance the profile section ui #51

- .github/workflows/greetings.yml
Fixed #96 
This pull request implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.
**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
- **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
- **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."
> Fixed #96 : Automated Greeting Workflow

- hiring-portal/src/App.js
- hiring-portal/src/CSS/backtotop.css
- hiring-portal/src/Components/BackToTop.jsx
- hiring-portal/src/Components/Navbar.jsx
This PR resolves the Issue #82 
Added a Back to top arrow button, which on clicking, takes the user to the top of the page.
The button appears after the user scrolls down a little bit.
_also corrected the location of logo.png in navbar.jsx (the location of logo.png was given incorrect due to which the website wasn't running in my local machine)_
**How to Test**
1. Go to any page and scroll down a bit.
3. Click on the blue upward arrow button showing at the right bottom corner (It will take you to the top of the page)
**Checklist:**
> Added Back to top button

- hiring-portal/Backend/controllers/blogController.js
- hiring-portal/Backend/models/Blog.js
- hiring-portal/Backend/routes/blogRoutes.js
- hiring-portal/Backend/server.js
- hiring-portal/src/App.js
- hiring-portal/src/CSS/blog.css
- hiring-portal/src/CSS/createBlog.css
- hiring-portal/src/CSS/readMoreBlog.css
- hiring-portal/src/Components/BlogPage.jsx
- hiring-portal/src/Components/CreateBlog.jsx
- hiring-portal/src/Components/Navbar.jsx
- hiring-portal/src/Components/ReadMoreBlog.jsx
issue #104 
Added full functional blog page
You can create your own blog 
you can read all blog 
currently i am giving feature to delete on each blog (but it can be removed or we can give access to owner in future)
also given delete all funcanality
added read more page 
given id to every blog post to easy access
i have not focus on styling that much i am fully focused on funcanalities of blog section 
if any changes need comment below this PR related to function 
https://github.com/user-attachments/assets/e925a34e-94be-4d1f-ba34-22b5ddc05b70
- [✔️ ] New feature
**Checklist:**
- [✔️] I have tested my changes and verified that they work
- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have commented my code, particularly in hard-to-understand areas …
> Added full functional blog page

- hiring-portal/src/App.js
- hiring-portal/src/CSS/termsAndConditions.css
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/TermsAndConditions.jsx
issue #106  
- [✅ ] New feature
**Checklist:**
- [ ✅] I have tested my changes and verified that they work
- [ ✅] My code follows the style guidelines of this project
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [ ✅] My changes generate no new warnings
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [ ✅] New and existing unit tests pass locally with my changes
> Added terms and condition page

- hiring-portal/src/CSS/jobpage.css
- hiring-portal/src/Components/Jobpage.jsx
add ed a clear all button by which all the filters are cleared at once
**please add gssoc-ext and level1 label before merge**
> added clear all button    issue #131

- README.md
#142  
This pull request updates the README file to include clear contribution guidelines, issue reporting format, directory structure, and features of the HireHub platform. These changes aim to enhance documentation for better understanding and usability for contributors and users. 
**Checklist:**
The updated documentation will assist new contributors in navigating the project effectively and clarify the project's features and structure.
> Update README.md #142

- hiring-portal/src/Components/JobGrid.jsx
- hiring-portal/src/Components/Profile.jsx
i added  skeleton loading when the jobs card are getting fetched 
**please add gssoc-ext and level1 before merge** @Yashgabani845
> Added skeleton placeholders in the jobs page    issue #146

- hiring-portal/Backend/controllers/userController.js
- hiring-portal/Backend/models/User.js
- hiring-portal/Backend/routes/userRoutes.js
- hiring-portal/package-lock.json
- hiring-portal/package.json
- hiring-portal/src/Components/Contactus.jsx
- hiring-portal/src/Components/Profile.jsx
i added a upload image button and added an api in the backend which lets the user upload his image 
**please add gssoc-ext and level2 labels before merege**
> added api to upload user image

- hiring-portal/Backend/controllers/bookmarksController.js
- hiring-portal/Backend/models/Bookmarks.js
- hiring-portal/Backend/routes/bookmarksRoute.js
- hiring-portal/Backend/server.js
#135 
This PR contains the backend functionality with apis written for bookmarking the jobs.
Jobs can be added,removed from bookmarks. 
There's also an api endpoint for fetching all user bookmarks.
**Checklist:**
Kindly review and merge this PR @Yashgabani845 
Also please add the hacktoberfest label
> Added bookmarks api on backend

- hiring-portal/src/CSS/job.css
- hiring-portal/src/Components/Job.jsx
i made the job page responsive 
image 2:
> made job page responsive issue #157

- README.md
#124
Added Contributor to readme.md
**Checklist:**
> Added Contributor to readme.md

- hiring-portal/Backend/controllers/userController.js
- hiring-portal/Backend/routes/userRoutes.js
- hiring-portal/src/App.js
- hiring-portal/src/Components/EditProfile.jsx
- hiring-portal/src/Components/Profile.jsx
#154 
Added Edit Profile Option
I changed the CGPA Here. Check it out.
**Checklist:**
> Edit Profile Done

- hiring-portal/src/CSS/postview.css
#169 
Add some CSS properties to make more engaging this image
before:
After  adding hover effect :
- [ x] New feature
**Checklist:**
- [ x] I have tested my changes and verified that they work
- [ x] My code follows the style guidelines of this project
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
> Add hover effect on the image.

- hiring-portal/.gitignore
- hiring-portal/Backend/ats.py
- hiring-portal/package-lock.json
- hiring-portal/src/App.js
- hiring-portal/src/CSS/resumeAnalyzer.css
- hiring-portal/src/Components/Navbar.jsx
- hiring-portal/src/Components/ResumeAnalyzer.jsx
issue #137 
https://github.com/user-attachments/assets/ca5e8c92-97de-45f3-853b-9a37406f685f
i didn't focus on ui i work on implementation of this ats resume tracker 
to use it 
you have to start you app
and as usual node server
and cd/backend 
python ats.py
dependency : pip install Flask Flask-CORS PyPDF2 google-generativeai python-dotenv
generate your api key generateAi 
then your python server will start and go on client side and add resume and jd and see your score !! 😊🚀
> Feat ATS tracking system added

- README.md
> updated Readme file 

- hiring-portal/src/App.js
- hiring-portal/src/Components/Error404.jsx
#212 
This update adds a custom `Error404` page to handle non-existent routes, improving user experience by displaying a friendly message and providing navigation options. The `Error404` component will be integrated into the project's routing system to render for invalid URLs. It will include a message like "Page Not Found" and a link back to the home page. The page will be styled to match the project's theme. Finally, routing will be updated to display the `Error404` page as the fallback route.
**Checklist:**
> Added Error404 page 

- README.md
Fixes:#209
this PR makes sure that it adds gssoc and Hacktober fest banner for this readme-file.
**Checklist:**
> Fixes:#209 - adding Gssoc and Hacktoberfest banner.

- hiring-portal/src/Components/Testimonial.jsx
issue #185 
https://github.com/user-attachments/assets/a76b1f53-4350-4d00-9fe9-fc2c3117abb1
Added a beautiful testimonial section we can easily append backend to it as i am featching the cards details form an array so its get easy to add API's
as it required effort to write that javascript logic 
can i get level 3 for it ?  , if any UI changes requrired just comment i will do it ASAP
> Builded testimonial section

- hiring-portal/src/CSS/backtotop.css
- hiring-portal/src/Components/Footer.jsx
issue #206 
https://github.com/user-attachments/assets/97cd8e8f-18d5-4c47-969c-6f339ac1db41
Added AI supported chatbot to intract with user 
, it will generate the answer by its own 
, trained on our website data !!
> Added AI based chatbot

- hiring-portal/package-lock.json
- hiring-portal/package.json
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/GoogleTranslate.jsx
Issue : #172 
I have added Multi-Language Support Using Language Translator API that will helps to convert the website text to the multiple country languages.
https://github.com/user-attachments/assets/f0906df1-4eb4-4ab9-a5ed-0811a54f5acc
**Checklist:**
> Multi-Language Support Using Language Translator

- Contributing.md
Fixes: [#220 ]
Closes:[#220 ]
I have enhanced the document and also added some new sections
Done the following changes :-
1) Enhanced the project structure
2) Added star our repository section
3) Added need help with the basics section
4) Updated first pull request steps section
5) Added additional method of contributing through GitHub desktop section
6) Added good coding practices section
7) Updated the pull request rules section
8) Updated issue report process section
**Checklist:**
- [] I have added tests that prove my fix is effective or that my feature works
> Done enhancement and also added some new sections

- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/Profile.jsx
resolved merge confilcts from footer.jsx and profile.jsx 
issue number : #225
please add relevant level before merge @Yashgabani845
> fixed merge confilcts

- hiring-portal/src/CSS/navbar.css
- hiring-portal/src/Components/Navbar.jsx
Nav Bar Bug Fixed
#182 
Now proper navigation is done for mobile view.
**Checklist:**
@Yashgabani845 Please check and merge it ASAP. 
[React App - Google Chrome 2024-10-23 21-33-05.zip](https://github.com/user-attachments/files/17495042/React.App.-.Google.Chrome.2024-10-23.21-33-05.zip)
> Fixed: #182 NavBar Icon Link in mobile view

- hiring-portal/Backend/controllers/contactController.js
- hiring-portal/Backend/routes/contactRoutes.js
- hiring-portal/package-lock.json
- hiring-portal/src/Components/Contactus.jsx
#226 
now you will also receive the email and the data will be saved to database (as before)
email demo:
**Checklist:**
please add gssoc-ext and level2 before merge @Yashgabani845
> added email functionality

- hiring-portal/Backend/controllers/userController.js
- hiring-portal/Backend/routes/userRoutes.js
- hiring-portal/src/Components/Profile.jsx
i added an option by which the user can add multiple skill in the profile  issue #227 
add skill option:
added the skill:
please add gssoc-ext and level3 before merge @Yashgabani845
> added add skill option

- hiring-portal/Backend/server.js
- hiring-portal/package-lock.json
- hiring-portal/package.json
fixed #156 
**Overview** : To improve the security of our Express application, we should implement the Helmet middleware. Helmet helps set various HTTP headers that protect against common vulnerabilities.
- Adds security headers to HTTP responses, helping to mitigate risks such as:
- Cross-Site Scripting (XSS)
- Clickjacking
- Content-Type sniffing
- Provides a foundational layer of security for our application.
> Add Helmet Middleware for Enhanced Security

- hiring-portal/Backend/Dockerfile
- hiring-portal/docker-compose.yml
- hiring-portal/src/Dockerfile
fixes #184 
This PR adds Docker setup to the application enabling containerization of the application.
Command to create the docker image and run inside the container : docker compose up --build
**Checklist:**
> Add Docker setup

- hiring-portal/src/App.js
- hiring-portal/src/Components/CreateBlog.jsx
Added the route for the create blog page .
Also implemented rich text editor in the create blog component (will revert back to original if not approved , if approved please raise the level of the PR).
https://github.com/user-attachments/assets/fb2c7ec1-2b94-4630-8bec-0108642dcb09
**Checklist:**
> Add route for createBlog

- README.md
Issue #203 
Updated a New Contact Section in Readme file For easy Communication
**Checklist:**
> Fixes #203 Fostering Contact Section

- README.md
- hiring-portal/package-lock.json
- hiring-portal/package.json
> add startup scripts

- hiring-portal/src/App.js
- hiring-portal/src/Components/Profile.jsx
- hiring-portal/src/Components/Signup.jsx
#155 
I added checks for required values and toast notification
**Checklist:**
> toast containers added

- hiring-portal/package-lock.json
- hiring-portal/package.json
- hiring-portal/src/App.js
- hiring-portal/src/Components/Navbar.jsx
- hiring-portal/src/Components/ResumeScreening.jsx
**I have utilised google api forth purpose** 
This chat interface is heighly informative and willhelpin screeing 
Scope:
We can add multiple predefined templtes for ease.
we can add file sharing, as of now gemein donot accept pdf formats so we have to provide text 
Pull Request Title
Resume Screening Feature Integration
Issue Reference: Resolves #232
Description: This pull request integrates the resume screening feature into the application. It enables users to input resume text, which is then analyzed using the AI-powered Gemini API. The analysis generates a detailed breakdown of the resume content, including sections such as Skills, Experience, Education, and more, presented in a clear, formatted structure.
Screenshots:
Screenshots or video demo of the resume input and AI-generated …
> Add resume screening Feature 

- hiring-portal/src/CSS/middleview.css
- hiring-portal/src/Components/MiddleView.jsx
- hiring-portal/src/Components/Navbar.jsx
- hiring-portal/src/Components/Profile.jsx
#264 
Time the carousels 
Uploading React App - Google Chrome 2024-10-28 22-41-58.mp4…
**Checklist:**
> timed the carousel and onclick rerouting

- hiring-portal/Backend/controllers/applicationController.js
- hiring-portal/package-lock.json
- hiring-portal/package.json
- hiring-portal/src/Components/ApplicationForm.jsx
#263
Added required fields check 
**Checklist:**
> Requiredfields check added

- hiring-portal/src/CSS/herosection.css
- hiring-portal/src/CSS/navbar.css
- hiring-portal/src/Components/Navbar.jsx
- hiring-portal/src/Components/Profile.jsx
---
**Issue Reference:**  
#274 
**Description:**  
- **Problem:** The search input icon overlaps with the input text, impacting visibility and usability.  
- **Navbar Alignment:** The navbar icon and text are not properly aligned.
**Before:**  
**After:**  
**Type of Change:**  
**Checklist:**  
**Additional Information:**  
This pull request addresses both desktop and mobile view issues to enhance user experience and improve search functionality.
> Feature/subodh Fix Search Input Icon Overlap and Navbar Alignment

- hiring-portal/Backend/middlewares/authMiddleware.js
- hiring-portal/Backend/routes/blogRoutes.js
- hiring-portal/src/CSS/ApplicationForm.css
- hiring-portal/src/Components/ApplicationForm.jsx
- package-lock.json
This PR adds footer and navbar to the applications page also improves the css of the form. 
**Checklist:**
> Fix Applications Page

- hiring-portal/Backend/ats.py
(Issue #254)
Improve Error Handling and File Format Validation in Resume Analysis API
It will display popup messages for validations, and other improvements is in python functionality, so no screenshots
**Checklist:**
> Added Error Handling and File Format Validation Messages (Issue #254)

- hiring-portal/Backend/.env.example
- hiring-portal/Backend/controllers/otpVerifyController.js
- hiring-portal/Backend/controllers/userController.js
- hiring-portal/Backend/models/User.js
- hiring-portal/Backend/routes/userRoutes.js
This PR adds otp verification for email so that the users emails are verified.
**Checklist:**
> Add Email OTP Verification

- PROJECT_STRUCTURE.md
- hiring-portal/src/Components/Faqs.jsx
- hiring-portal/src/Components/MiddleView.jsx
- repo_structure.txt
issue number #300
now it do not disappear when clicked:
removed this image which was appearing twice due to merge conflict
please review this pr @Yashgabani845
> fixed Home page error of faq section and other small issues

- PROJECT_STRUCTURE.md
- hiring-portal/src/App.js
- hiring-portal/src/Components/Spinner.jsx
- hiring-portal/src/PrivateRoute.jsx
- repo_structure.txt
issue number #286
created and added private route to the create blog so that only user who is logged in will be able to visit the page 
demo :
visit the create blog page 
it will check authentication:
if not login redirect to the login page:
please review and add level3 before merge @Yashgabani845
> added Private route in create blog page 

- hiring-portal/src/App.js
- hiring-portal/src/CSS/TermsOfUse.module.css
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/TermsOfUse.jsx
issue : #312 
Description
This PR introduces a new "Terms of Use" page to the application, outlining the terms and conditions that govern the use of our services. The document includes various sections that define user obligations, intellectual property rights, limitation of liability, dispute resolution, and more, providing a comprehensive legal framework for users.
Changes Made
Created a new page named TermsOfUse.
Structured the content into relevant sections for clarity:
Acceptance of Terms
User Obligations
Intellectual Property Rights
Limitation of Liability
Indemnification
Termination Clause
Governing Law
Modification of Terms
Legal Compliance
Dispute Resolution
Added a clean clear terms of use page with beautiful ui
for both light and dark theme
> Added Terms of use page

- hiring-portal/src/CSS/SigninWithGoogle.module.css
- hiring-portal/src/CSS/signin.css
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/SignInWithGoogle.jsx
- hiring-portal/src/Components/Signin.jsx
- hiring-portal/src/firebase/firebase.js
issue : #310
https://github.com/user-attachments/assets/2f8f0354-780b-45f0-95b2-f293b1540f35
Added a signin with google component
writed modular code so that this component can be used anywhere in your application 
beautifully designed
you can use any info of the user given in mail
> Added sign in with google feature

- hiring-portal/src/CSS/contributor.css
- hiring-portal/src/Components/ContributorPage.jsx
issue : #321 
https://github.com/user-attachments/assets/1e78f9cf-c3cf-42f4-84eb-3d72ed0a5c86
Added open issue section 
in both dark and light theme
also fixes that dark button on header
make clean clear ui 
show all the relavant info about issue 
also link to issue so that user can directly go to that issue
> Added open issue card in both light and dark theme

- hiring-portal/src/Components/Navbar.jsx
issue : #322
https://github.com/user-attachments/assets/91d7cce9-5836-413f-a4b9-55b5ea038542
Added toaster on click to post job if user is not logged in 
enhance user experience
> Added toaster on click to posting job

- hiring-portal/Backend/controllers/visitorController.js
- hiring-portal/Backend/models/Visitor.js
- hiring-portal/Backend/routes/visitorRoutes.js
- hiring-portal/Backend/server.js
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/VisitorCount.jsx
issue : #307 
Added Backend api for total visitor count
real time fetching and updating the data for visitor
> Implemented CURD backend Api for total visitor count

- PROJECT_STRUCTURE.md
- hiring-portal/Backend/ats.py
- repo_structure.txt
#302
Implemented a caching mechanism that checks if a resume and job description pair has been previously analyzed.
If a match is found in the cache, return the cached result.
If not, perform the analysis, store the result in the cache, and then return it to the user.
**Checklist:**
Added a dictionary list for this caching storage implementation
> Implemented Analysis Caching to Optimize Performance

- hiring-portal/package-lock.json
- hiring-portal/package.json
- hiring-portal/src/App.css
- hiring-portal/src/App.js
- hiring-portal/src/CSS/About.module.css
- hiring-portal/src/CSS/middleview.module.css
- hiring-portal/src/CSS/navbar.module.css
- hiring-portal/src/Components/ApplicationForm.jsx
- hiring-portal/src/Components/HeroSection.jsx
- hiring-portal/src/Components/MiddleView.jsx
- hiring-portal/src/Components/Navbar.jsx
- hiring-portal/src/Components/Testimonial.jsx
Reverts Yashgabani845/hiring-portal#297
> Revert "Implement Dark Theme Feature ✨"

- hiring-portal/src/Components/Testimonial.jsx
issue #336 
https://github.com/user-attachments/assets/1350d427-ea85-4b3f-8db9-5f62c02dbe26
fixes the alignment of content in testimonial card
and maked it auto scrollable
> Enhance the styling of testimonial page and maked it autoscrollable

- hiring-portal/src/App.js
- hiring-portal/src/CSS/Stories.module.css
- hiring-portal/src/Components/Footer.jsx
- hiring-portal/src/Components/Stories.jsx
issue : #337
https://github.com/user-attachments/assets/fd01a3cc-4e0c-4997-a437-ab8c5750d31d
This PR adds a Stories Page where users can share job interview experiences,
career advice, and more
. Users can submit stories with a title, content, and category, and view others' posts
. Stories are stored for persistence, 
Clean and clear UI
- [ X] New feature
**Checklist:**
- [ X] I have tested my changes and verified that they work
- [ X] My code follows the style guidelines of this project
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing …
> Implement Stories Page for User Job Interview Experience Sharing ✨🚀

- hiring-portal/Backend/controllers/discussionController.js
- hiring-portal/Backend/models/discussion.js
- hiring-portal/Backend/routes/discussionRoutes.js
- hiring-portal/Backend/server.js
- hiring-portal/src/CSS/DiscussionSection.module.css
- hiring-portal/src/Components/DiscussionSection.jsx
Issue : #341 
At frontend you can see there are 2 question  at answered and  unanswered
This is how data is saved on backend !!
if question is unanswered or answered
handling both in one api call to remove load from the server
Quality and modular code for better maintainance
Real time data featching , writing , updating at backend / database !!
- [X ] New feature
**Checklist:**
- [ X] I have tested my changes and verified that they work
- [ X] My code follows the style guidelines of this project
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and …
> Writed Efficient backend API for Discussion forum  | Clean and clear schema 🚀

- hiring-portal/Backend/controllers/blogController.js
- hiring-portal/Backend/routes/blogRoutes.js
- hiring-portal/src/App.js
- hiring-portal/src/CSS/blog.module.css
- hiring-portal/src/Components/BlogPage.jsx
issue number #328 
added pagination frontend backend both:
https://github.com/user-attachments/assets/74e0e2e2-0c89-4cd6-972b-62a8f7767e8b
added skeleton loading:
improved the ui
1) fixed the create blog button so user can see it while scrolling
2) added scroll on the blogs page
3) fixed the alignment of the blogs page 
please review and merge this pr @Yashgabani845
> add Pagination in blogs page

- hiring-portal/src/CSS/navbar.module.css
- hiring-portal/src/Components/Navbar.jsx
> Refactor Navbar for Improved Usability and Design ✨ 

- hiring-portal/src/CSS/navbar.module.css
BEFORE 
AFTER MERGING THIS PR
- [X ] Bug fix
**Checklist:**
- [ X] I have tested my changes and verified that they work
- [ X] My code follows the style guidelines of this project
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
> Fixes the alignment of navbar in responsive screen 

- hiring-portal/Backend/controllers/postsController.js
- hiring-portal/Backend/models/postModel.js
- hiring-portal/Backend/routes/storiesRoutes.js
- hiring-portal/Backend/server.js
- hiring-portal/src/Components/Stories.jsx
issue : #337 
This PR implements the backend for the Stories page, including the following:
GET /api/posts: Fetches all the stories (posts) from the database.
POST /api/posts: Allows users to create and save new stories by submitting title, content, and category data.
The data is stored in a MongoDB database using Mongoose, and the backend handles both the creation and retrieval of posts.
Changes include:
Creation of routes and controllers for handling posts.
Integration of Mongoose for database interaction.
Validation to ensure necessary fields are provided before saving a new post.
This sets up the backend to support the stories functionality on the frontend.
- [X ] New feature
**Checklist:**
- [ X] I have tested my changes and verified that they work
- [ X] My code …
> Build Backend for Stories Page: Implement POST and GET Routes ✨🚀

- hiring-portal/package-lock.json
- hiring-portal/package.json
- hiring-portal/src/Components/Contactus.jsx
> Changed the Twitter icon to X !!

- hiring-portal/src/CSS/faqSection.module.css
**Issue Reference:**  
#353
**Description:**  
This PR includes the following changes:
- Improved the FAQ section UI by enhancing the layout and hover effects.
- Optimized the responsiveness of the FAQ section for mobile devices.
- Updated the design to use only blue and white colors, aligning with the brand's theme.
**Screenshots:**  
**Checklist:**
**Additional Information:**  
- The updated FAQ section now utilizes more interactive hover effects, making the design visually appealing.
- There are additional changes to the responsiveness of the page to improve viewing on mobile devices (screens < 768px).
> Enhancing the FAQ page !!!

- hiring-portal/src/CSS/About.module.css
Reverts Yashgabani845/hiring-portal#373
> Revert "Added Hovering Effects on cards !!"
